<!-- Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ -->
<script setup>
import AppShell from '../../components/AppShell.vue'
import MetricGrid from '../../components/MetricGrid.vue'
import StatusPill from '../../components/StatusPill.vue'
import { domain, adminMetrics, records, loads, issues, chartActual, chartTarget } from '../../config/domain'
</script>

<template><AppShell mode="admin">
  <div class="page-head"><div><span class="breadcrumb">{{ domain.adminBreadcrumb }}</span><h1>{{ domain.adminTitle }}</h1><p>{{ domain.adminSubtitle }}</p></div><div class="head-actions"><button class="secondary">{{ domain.exportAction }}</button><button class="primary">{{ domain.createAction }}</button></div></div>
  <MetricGrid :items="adminMetrics"/>
  <div class="dashboard-grid aps-grid">
    <section class="panel output-panel"><div class="panel-head"><div><h2>{{ domain.chartTitle }}</h2><p>{{ domain.chartSubtitle }}</p></div><div class="legend"><span><i class="actual"></i>实际</span><span><i></i>目标</span></div></div><div class="line-chart"><div class="chart-scale"><span>100</span><span>75</span><span>50</span><span>0</span></div><svg viewBox="0 0 720 190" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" :stop-color="domain.theme.primary" stop-opacity=".25"/><stop offset="1" :stop-color="domain.theme.primary" stop-opacity="0"/></linearGradient></defs><polyline :points="chartTarget.map((v,i)=>`${25+i*48},${176-v*1.45}`).join(' ')" fill="none" stroke="#b4bcc5" stroke-width="2" stroke-dasharray="5 5"/><polygon :points="'25,176 '+chartActual.map((v,i)=>`${25+i*48},${176-v*1.45}`).join(' ')+' 681,176'" fill="url(#area)"/><polyline :points="chartActual.map((v,i)=>`${25+i*48},${176-v*1.45}`).join(' ')" fill="none" :stroke="domain.theme.primary" stroke-width="3"/><circle v-for="(v,i) in chartActual" :key="i" :cx="25+i*48" :cy="176-v*1.45" r="3.5" fill="#fff" :stroke="domain.theme.primary" stroke-width="2"/></svg><div class="chart-x"><span v-for="h in domain.chartLabels" :key="h">{{ h }}</span></div></div></section>
    <section class="panel line-load"><div class="panel-head"><div><h2>{{ domain.loadTitle }}</h2><p>{{ domain.loadSubtitle }}</p></div><router-link to="/admin/resources">查看详情</router-link></div><div class="load-row" v-for="x in loads" :key="x[0]"><div><b>{{ x[0] }}</b><small>{{ x[2] }}</small></div><span class="load-track"><i :style="{width:x[1]+'%'}" :class="{hot:x[1]>90}"></i></span><em>{{ x[1] }}%</em></div></section>
    <section class="panel orders-panel"><div class="panel-head"><div><h2>{{ domain.recordsTitle }}</h2><p>{{ domain.recordsSubtitle }}</p></div><router-link to="/admin/work-orders">全部{{ domain.recordName }}</router-link></div><table><thead><tr><th>{{ domain.recordName }} / {{ domain.itemName }}</th><th>{{ domain.unitName }}</th><th>{{ domain.batchName }}</th><th>{{ domain.planName }} / {{ domain.doneName }}</th><th>进度</th><th>期限</th><th>状态</th></tr></thead><tbody><tr v-for="w in records.slice(0,4)" :key="w.no"><td><b>{{ w.no }}</b><small>{{ w.name }}</small></td><td>{{ w.unit }}</td><td>{{ w.batch }}</td><td>{{ w.plan }} / {{ w.done }}</td><td><span class="progress"><i :style="{width:w.progress+'%'}"></i></span>{{ w.progress }}%</td><td>{{ w.due }}</td><td><StatusPill :text="w.status"/></td></tr></tbody></table></section>
    <section class="panel exception-panel"><div class="panel-head"><div><h2>{{ domain.issueTitle }}</h2><p>{{ domain.issueSubtitle }}</p></div><span class="count-badge">{{ issues.length }}</span></div><div class="exception" v-for="(x,i) in issues" :key="x.title"><span :class="i===0?'alarm-code':i===1?'quality-code':'material-code'">{{ x.type }}</span><div><b>{{ x.title }}</b><small>{{ x.detail }}</small></div><em>{{ x.status }}</em></div></section>
  </div>
</AppShell></template>
