<!-- Copyright 2026 上海如静知华信息科技有限公司 -->
<script setup>
import { ref, computed } from 'vue'
import AppShell from '../../components/AppShell.vue'
import StatusPill from '../../components/StatusPill.vue'
import { domain, records } from '../../config/domain'
const tab = ref('全部'), keyword = ref('')
const rows = computed(() => records.filter(w => (tab.value === '全部' || w.status === tab.value) && (w.no.includes(keyword.value) || w.name.includes(keyword.value))))
</script>
<template><AppShell mode="admin"><div class="page-head"><div><span class="breadcrumb">{{ domain.listBreadcrumb }}</span><h1>{{ domain.recordName }}台账</h1><p>{{ domain.listSubtitle }}</p></div><div class="head-actions"><button class="secondary">批量导入</button><button class="primary">+ 新建{{ domain.recordName }}</button></div></div><section class="panel list-panel"><div class="summary-strip"><div v-for="s in domain.listSummary" :key="s[0]"><span>{{ s[0] }}</span><b :class="{'danger-text':s[2]}">{{ s[1] }}</b></div></div><div class="toolbar"><div class="tabs"><button v-for="t in domain.tabs" :key="t" :class="{active:tab===t}" @click="tab=t">{{ t }}</button></div><div class="filters"><input v-model="keyword" :placeholder="`搜索${domain.recordName}编号或${domain.itemName}`"/><select><option>全部{{ domain.unitName }}</option><option v-for="u in [...new Set(records.map(x=>x.unit))]" :key="u">{{ u }}</option></select><button class="secondary">筛选</button></div></div><table class="workorder-table"><thead><tr><th>优先级</th><th>{{ domain.recordName }}</th><th>{{ domain.itemName }}</th><th>{{ domain.unitName }}</th><th>{{ domain.planName }}</th><th>{{ domain.doneName }} / {{ domain.exceptionName }}</th><th>完成进度</th><th>期限</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="w in rows" :key="w.no"><td><span class="priority" :class="w.priority">{{ w.priority }}</span></td><td><b>{{ w.no }}</b><small>{{ w.batch }}</small></td><td><b>{{ w.name }}</b><small>{{ w.code }}</small></td><td>{{ w.unit }}<small>{{ w.group }}</small></td><td>{{ w.plan }} {{ domain.unitLabel }}</td><td>{{ w.done }} <small>{{ domain.exceptionName }} {{ w.exception }}</small></td><td><span class="progress wide-progress"><i :style="{width:w.progress+'%'}"></i></span><b>{{ w.progress }}%</b></td><td>{{ w.due }}</td><td><StatusPill :text="w.status"/></td><td><button class="more">•••</button></td></tr></tbody></table><div class="pagination"><span>共 {{ rows.length }} 条记录</span><div><button>‹</button><button class="active">1</button><button>›</button></div></div></section></AppShell></template>
