<!-- Copyright 2026 上海如静知华信息科技有限公司 -->
<script setup>
import { ref, computed } from 'vue'
import AppShell from '../../components/AppShell.vue'
import { domain, records } from '../../config/domain'
const record = records[0], done = ref(domain.reportDefaults[0]), exception = ref(domain.reportDefaults[1]), stage = ref(domain.steps[2]), submitted = ref(false)
const total = computed(() => Number(done.value) + Number(exception.value))
function submit(){submitted.value=true;setTimeout(()=>submitted.value=false,2600)}
</script>
<template><AppShell mode="shopfloor"><div class="page-head"><div><span class="breadcrumb">{{ domain.fieldBreadcrumb }} / {{ domain.reportAction }}</span><h1>{{ domain.reportTitle }}</h1><p>{{ domain.reportSubtitle }}</p></div><router-link class="secondary" to="/shopfloor">返回工作台</router-link></div><div v-if="submitted" class="success-toast">✓ {{ domain.reportSuccess }}</div><div class="report-layout"><section class="panel report-form"><div class="report-order"><div><span>{{ domain.recordName }}</span><b>{{ record.no }}</b><small>{{ record.name }} · {{ domain.batchName }} {{ record.batch }}</small></div><div class="remaining"><span>剩余{{ domain.unitLabel }}</span><strong>{{ record.plan-record.done }}</strong><small>{{ domain.unitLabel }}</small></div></div><div class="form-section"><h2>本次记录</h2><div class="form-grid"><label><span>处理环节</span><select v-model="stage"><option v-for="s in domain.steps" :key="s">{{ s }}</option></select></label><label><span>记录人</span><input :value="domain.fieldUser" disabled/></label><label class="quantity good"><span>{{ domain.doneName }}</span><div><button @click="done=Math.max(0,done-1)">−</button><input v-model.number="done" type="number"/><button @click="done++">＋</button></div></label><label class="quantity defect"><span>{{ domain.exceptionName }}</span><div><button @click="exception=Math.max(0,exception-1)">−</button><input v-model.number="exception" type="number"/><button @click="exception++">＋</button></div></label><label><span>开始时间</span><input value="2026-08-01 09:48"/></label><label><span>结束时间</span><input value="2026-08-01 10:26"/></label><label class="full-field"><span>备注</span><textarea :placeholder="domain.reportPlaceholder"></textarea></label></div></div><div class="report-submit"><div><span>本次合计</span><b>{{ total }} {{ domain.unitLabel }}</b><small>{{ domain.reportFootnote }}</small></div><button class="primary" @click="submit">确认提交</button></div></section><div class="report-aside"><section class="panel"><div class="panel-head"><div><h2>{{ domain.ruleTitle }}</h2><p>{{ domain.ruleSubtitle }}</p></div></div><dl class="spec-list"><div v-for="r in domain.rules" :key="r[0]"><dt>{{ r[0] }}</dt><dd :class="{'ok':r[2]}">{{ r[1] }}</dd></div></dl></section><section class="panel"><div class="panel-head"><div><h2>今日累计</h2><p>08:00 至当前</p></div></div><div class="shift-total"><div v-for="s in domain.fieldTotals" :key="s[1]"><b>{{ s[0] }}</b><span>{{ s[1] }}</span></div></div></section></div></div></AppShell></template>
